"""create business tables and update users

Revision ID: 64ff9c9de6ba
Revises: 6b99271a762d
Create Date: 2026-08-10 08:28:28.150141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '64ff9c9de6ba'
down_revision: Union[str, Sequence[str], None] = '6b99271a762d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='上传者（系统导入则为空）'),
    sa.Column('kb_type', sa.Integer(), nullable=False, comment='知识库类型：0=等保标准库，1=企业本地库，2=历史标书库'),
    sa.Column('doc_title', sa.String(length=255), nullable=False, comment='文档标题'),
    sa.Column('doc_source', sa.String(length=255), nullable=True, comment='来源，如 GB/T 22239-2019'),
    sa.Column('file_path', sa.String(length=512), nullable=False, comment='原始文件路径'),
    sa.Column('chunk_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='切分后的向量块数'),
    sa.Column('status', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='状态：0=待处理，1=已向量化，2=处理失败'),
    sa.Column('created_at', sa.BigInteger(), server_default=sa.text('(unix_timestamp())'), nullable=False, comment='创建时间（Unix 秒）'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_documents_kb_type'), 'kb_documents', ['kb_type'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户'),
    sa.Column('role_type', sa.Integer(), nullable=False, comment='角色类型：0=商务，1=技术'),
    sa.Column('intent_type', sa.Integer(), nullable=False, comment='意图类型：0=对话助手，1=招投标，2=测评核查，3=知识问答'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='会话标题'),
    sa.Column('created_at', sa.BigInteger(), server_default=sa.text('(unix_timestamp())'), nullable=False, comment='会话创建时间（Unix 秒）'),
    sa.Column('updated_at', sa.BigInteger(), server_default=sa.text('(unix_timestamp())'), nullable=False, comment='会话更新时间（Unix 秒）'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('assessment_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='所属会话'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户'),
    sa.Column('system_level', sa.Integer(), nullable=False, comment='等保级别：0=二级，1=三级，2=四级'),
    sa.Column('checklist_code', sa.String(length=32), nullable=False, comment='等保控制点编号，如 8.1.4.1'),
    sa.Column('checklist_name', sa.String(length=128), nullable=False, comment='控制点名称，如 身份鉴别'),
    sa.Column('assessment_command', sa.String(length=512), nullable=True, comment='测评命令'),
    sa.Column('screenshot_path', sa.String(length=512), nullable=True, comment='测评截图文件路径'),
    sa.Column('vlm_analysis', sa.JSON(), nullable=True, comment='VLM 截图分析结果'),
    sa.Column('human_record', sa.Text(), nullable=True, comment='组员人工填写的结果记录'),
    sa.Column('comparison_result', sa.JSON(), nullable=True, comment='AI 与人工记录比对结果'),
    sa.Column('kb_references', sa.JSON(), nullable=True, comment='核查时检索到的企业本地知识库特殊情况说明'),
    sa.Column('confidence', sa.Float(), server_default=sa.text('0.0'), nullable=False, comment='置信度 0.0~1.0'),
    sa.Column('status', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='状态：0=待测评，1=待核查，2=核查中，3=自动通过，4=待人工复核，5=已确认，6=异常'),
    sa.Column('created_at', sa.BigInteger(), server_default=sa.text('(unix_timestamp())'), nullable=False, comment='创建时间（Unix 秒）'),
    sa.Column('updated_at', sa.BigInteger(), server_default=sa.text('(unix_timestamp())'), nullable=False, comment='更新时间（Unix 秒）'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_records_session_id'), 'assessment_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_assessment_records_status'), 'assessment_records', ['status'], unique=False)
    op.create_index(op.f('ix_assessment_records_user_id'), 'assessment_records', ['user_id'], unique=False)
    op.create_table('bidding_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='所属会话'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户'),
    sa.Column('tender_title', sa.String(length=255), nullable=True, comment='招标项目名称'),
    sa.Column('tender_url', sa.String(length=512), nullable=True, comment='招标公告 URL'),
    sa.Column('tender_file_path', sa.String(length=512), nullable=True, comment='解析后的招标文件路径'),
    sa.Column('bidding_sections', sa.JSON(), nullable=True, comment='投标文件各部分内容'),
    sa.Column('compliance_result', sa.JSON(), nullable=True, comment='废标项与评分表检查结果'),
    sa.Column('reference_doc_ids', sa.JSON(), nullable=True, comment='引用的历史标书文档 ID 列表'),
    sa.Column('status', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='状态：0=搜索中，1=已解析，2=编写中，3=废标检查中，4=待人工审核，5=已完成，6=异常终止'),
    sa.Column('created_at', sa.BigInteger(), server_default=sa.text('(unix_timestamp())'), nullable=False, comment='创建时间（Unix 秒）'),
    sa.Column('updated_at', sa.BigInteger(), server_default=sa.text('(unix_timestamp())'), nullable=False, comment='更新时间（Unix 秒）'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bidding_tasks_status'), 'bidding_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_bidding_tasks_user_id'), 'bidding_tasks', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户'),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='所属会话'),
    sa.Column('role', sa.Integer(), nullable=False, comment='消息角色：0=user，1=assistant'),
    sa.Column('request_id', sa.String(length=64), nullable=False, comment='请求 ID'),
    sa.Column('content', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=False, comment='消息内容'),
    sa.Column('tool_calls', sa.JSON(), nullable=True, comment='Agent 工具调用记录'),
    sa.Column('file_extracted_text', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True, comment='从文件中提取的完整文本'),
    sa.Column('created_at', sa.BigInteger(), server_default=sa.text('(unix_timestamp())'), nullable=False, comment='创建时间（Unix 秒）'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_request_id'), 'chat_messages', ['request_id'], unique=False)
    op.create_index('ix_chat_messages_session_created', 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_table('review_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='所属会话'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='提交审核的用户'),
    sa.Column('task_type', sa.Integer(), nullable=False, comment='任务类型：0=报价审核，1=低置信度复核'),
    sa.Column('source_type', sa.Integer(), nullable=False, comment='来源类型：0=招投标任务，1=测评核查记录'),
    sa.Column('source_id', sa.Integer(), nullable=False, comment='关联 bidding_tasks.id 或 assessment_records.id'),
    sa.Column('review_data', sa.JSON(), nullable=False, comment='待审核数据快照'),
    sa.Column('reviewer_id', sa.Integer(), nullable=True, comment='实际审核人'),
    sa.Column('review_result', sa.Integer(), nullable=True, comment='审核结果：0=通过，1=驳回，2=修改后通过'),
    sa.Column('review_comment', sa.Text(), nullable=True, comment='审核意见'),
    sa.Column('status', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='状态：0=待审核，1=已审核，2=已取消'),
    sa.Column('created_at', sa.BigInteger(), server_default=sa.text('(unix_timestamp())'), nullable=False, comment='创建时间（Unix 秒）'),
    sa.Column('reviewed_at', sa.BigInteger(), nullable=True, comment='审核完成时间（Unix 秒）'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_tasks_status'), 'review_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_review_tasks_task_type'), 'review_tasks', ['task_type'], unique=False)
    op.create_table('topology_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='所属会话'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户'),
    sa.Column('asset_file_path', sa.String(length=512), nullable=False, comment='资产核查表文件路径'),
    sa.Column('topology_data', sa.JSON(), nullable=True, comment='网络拓扑图数据'),
    sa.Column('topology_summary', sa.Text(), nullable=True, comment='拓扑结构文字描述'),
    sa.Column('status', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='状态：0=生成中，1=已完成，2=生成失败'),
    sa.Column('created_at', sa.BigInteger(), server_default=sa.text('(unix_timestamp())'), nullable=False, comment='创建时间（Unix 秒）'),
    sa.Column('updated_at', sa.BigInteger(), server_default=sa.text('(unix_timestamp())'), nullable=False, comment='更新时间（Unix 秒）'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topology_records_session_id'), 'topology_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_topology_records_status'), 'topology_records', ['status'], unique=False)
    op.add_column('users', sa.Column('role', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='角色：0=商务，1=技术'))
    op.add_column('users', sa.Column('display_name', sa.String(length=64), server_default=sa.text("''"), nullable=False, comment='显示名称'))
    op.add_column('users', sa.Column('email', sa.String(length=128), nullable=True, comment='邮箱'))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'))
    op.add_column('users', sa.Column('status', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='状态：0=禁用，1=正常'))
    op.add_column('users', sa.Column('created_at', sa.BigInteger(), server_default=sa.text('(unix_timestamp())'), nullable=False, comment='创建时间（Unix 秒）'))
    op.add_column('users', sa.Column('updated_at', sa.BigInteger(), server_default=sa.text('(unix_timestamp())'), nullable=False, comment='更新时间（Unix 秒）'))
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               type_=sa.String(length=64),
               comment='登录用户名',
               existing_comment='用户名',
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=255),
               existing_comment='密码 bcrypt 哈希',
               existing_nullable=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.drop_column('users', 'create_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False, comment='创建时间'))
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_comment='密码 bcrypt 哈希',
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='用户名',
               existing_comment='登录用户名',
               existing_nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'status')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'email')
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'role')
    op.drop_index(op.f('ix_topology_records_status'), table_name='topology_records')
    op.drop_index(op.f('ix_topology_records_session_id'), table_name='topology_records')
    op.drop_table('topology_records')
    op.drop_index(op.f('ix_review_tasks_task_type'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_status'), table_name='review_tasks')
    op.drop_table('review_tasks')
    op.drop_index('ix_chat_messages_session_created', table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_request_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_bidding_tasks_user_id'), table_name='bidding_tasks')
    op.drop_index(op.f('ix_bidding_tasks_status'), table_name='bidding_tasks')
    op.drop_table('bidding_tasks')
    op.drop_index(op.f('ix_assessment_records_user_id'), table_name='assessment_records')
    op.drop_index(op.f('ix_assessment_records_status'), table_name='assessment_records')
    op.drop_index(op.f('ix_assessment_records_session_id'), table_name='assessment_records')
    op.drop_table('assessment_records')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_kb_documents_kb_type'), table_name='kb_documents')
    op.drop_table('kb_documents')
    # ### end Alembic commands ###
