"""create resources metadata table

Revision ID: 774abeb26107
Revises: 64ff9c9de6ba
Create Date: 2026-08-10 08:35:54.130629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '774abeb26107'
down_revision: Union[str, Sequence[str], None] = '64ff9c9de6ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='资源主键ID'),
    sa.Column('resource_type', sa.Integer().with_variant(mysql.TINYINT(), 'mysql'), nullable=False, comment='资源类型：0=文档（PDF/Word/Excel），1=图片（测评截图）'),
    sa.Column('storage_scene', sa.Integer().with_variant(mysql.TINYINT(), 'mysql'), server_default=sa.text('0'), nullable=False, comment='存储场景：0=长过期（1个月），1=短过期（2小时），2=只提取内容不存原文件'),
    sa.Column('upload_purpose', sa.Integer().with_variant(mysql.TINYINT(), 'mysql'), server_default=sa.text('0'), nullable=False, comment='上传用途：0=普通资源，1=招标文件，2=历史标书，3=测评截图，4=资产核查表'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='用户上传原始文件名'),
    sa.Column('file_hash', sa.String(length=64), nullable=False, comment='文件MD5，去重核心字段'),
    sa.Column('storage_path', sa.String(length=512), nullable=False, comment='MinIO对象存储路径'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='上传用户ID'),
    sa.Column('expire_time', sa.BigInteger(), nullable=True, comment='资源过期时间（Unix秒时间戳）'),
    sa.Column('created_at', sa.BigInteger(), server_default=sa.text('(unix_timestamp())'), nullable=False, comment='创建时间（Unix 秒）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash', 'user_id', name='uk_file_hash_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resources')
    # ### end Alembic commands ###
